[metadata]
name = "Ring VRF"
description = "Ring VRF implementation using zkSNARKs or does it?"
authors = ["Alistair, Davide, Jeff, Syed, Sergey"]

[config]
template = "specification_template.md"

[sections]
## VRF
vrf = "dleq_vrf/src/vrf.rs"
# DLEQ VRF
dleq-vrf-preliminaries = "dleq_vrf/src/lib.rs"
## Pedersen VRF
pedersen-vrf = "dleq_vrf/src/pedersen.rs"
